apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.environment }}-cert
spec:
  secretName: {{ .Values.environment }}-cert-key
  issuerRef:
    name: cluster-dns-issuer
    kind: ClusterIssuer
  dnsNames:
  - {{ if eq .Values.environment "prod" }}{{ .Values.domain }}{{ else }}{{ .Values.environment }}.{{ .Values.domain }}{{ end }}
  - {{ if eq .Values.environment "prod" }}"*.{{ .Values.domain }}"{{ else }}"*.{{ .Values.environment }}.{{ .Values.domain }}"{{ end }}